# Generated by Django 3.0.5 on 2020-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Option4',
            field=models.CharField(default='sds', max_length=2000),
            preserve_default=False,
        ),
    ]
