# Generated by Django 3.0.5 on 2020-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_questions_option4'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Attempted',
            field=models.BooleanField(default=False),
        ),
    ]
