# Generated by Django 3.0.5 on 2020-12-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_answers_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='option1',
            field=models.CharField(default='s', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='option2',
            field=models.CharField(default='sds', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='option3',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='option4',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.CharField(default=1, max_length=8000),
            preserve_default=False,
        ),
    ]
