# Generated by Django 3.0.5 on 2020-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_answers_explaination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Single_Answer',
            field=models.BooleanField(default=True),
        ),
    ]
